### ISSUE TITLE
Return a list of task names

### ISSUE THREAD

**Issue by madskristensen** [sayedihashimi/alfredps#4]
By executing `alfred list` all the tasks specified in the local Alfred.ps1 file should be listed in a newline separated list

**Comment by sayedihashimi** [comment]
@madskristensen ok I've added it. In your C# you should do the following.
 1. Install alfred with ```(new-object Net.WebClient).DownloadString('https://raw.githubusercontent.com/sayedihashimi/alfredps/master/getalfred.ps1') | iex```
 1. ```alfred -scriptpath <path> -list```

Here is a reference on how to invoke PowerShell from C# http://blogs.msdn.com/b/kebab/archive/2014/04/28/executing-powershell-scripts-from-c.aspx. Let me know if you need any help with that.

What else is needed?
